# Generated by Django 5.1.7 on 2025-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TotalViewApiDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDUSUARIO", models.IntegerField()),
                ("DATA_REFERENCIA", models.DateField(blank=True, null=True)),
                ("LOGIN", models.DateTimeField(blank=True, null=True)),
                ("LOGOUT", models.DateTimeField(blank=True, null=True)),
                ("PLATAFORMA", models.CharField(blank=True, max_length=255, null=True)),
                ("ATUALIZACAO", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
