# Generated by Django 5.1.7 on 2025-03-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TotalViewApiDB",
            fields=[
                ("IDUSUARIO", models.IntegerField(primary_key=True, serialize=False)),
                ("DATA_REFERENCIA", models.DateField()),
                ("LOGIN", models.DateTimeField()),
                ("LOGOUT", models.DateTimeField()),
                ("PLATAFORMA", models.CharField(max_length=255)),
                ("ATUALIZACAO", models.DateTimeField()),
            ],
        ),
    ]
